[build]
  command = "npm run build"  # Mettez ici la commande pour construire votre site

[functions]
  # Si vous utilisez des fonctions Netlify, configurez-les ici

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"


[[redirects]]
  from = "/myapi/*"
  to = "https://foot-stat.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
